kind: Deployment
metadata:
  name: squashers
  labels:
    app: squashers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: squashers
  template:
    metadata:
      labels:
        app: squashers
    spec:
      containers:
      - name: squashers
        image: zaralink/ultimate-cicd:2
        ports:
        - containerPort: 8080
